name: mini_app_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
